services:
  node1:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node1
      - DATA_DIR=/data
      - SEED=true
      - NODES=node2,node3,node4,node5,node6,node7,node8,node9,node10,node11,node12,node13,node14,node15,node16,node17,node18,node19,node20,node21,node22,node23,node24,node25,node26,node27,node28,node29,node30
    ports:
      - "8001:8000"
    volumes:
      - ./data/node1:/data
    networks:
      - kadnet

  node2:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node2
      - DATA_DIR=/data
    ports:
      - "8002:8000"
    volumes:
      - ./data/node2:/data
    networks:
      - kadnet

  node3:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node3
      - DATA_DIR=/data
    ports:
      - "8003:8000"
    volumes:
      - ./data/node3:/data
    networks:
      - kadnet

  node4:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node4
      - DATA_DIR=/data
    ports:
      - "8004:8000"
    volumes:
      - ./data/node4:/data
    networks:
      - kadnet

  node5:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node5
      - DATA_DIR=/data
    ports:
      - "8005:8000"
    volumes:
      - ./data/node5:/data
    networks:
      - kadnet

  node6:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node6
      - DATA_DIR=/data
    ports:
      - "8006:8000"
    volumes:
      - ./data/node6:/data
    networks:
      - kadnet

  node7:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node7
      - DATA_DIR=/data
    ports:
      - "8007:8000"
    volumes:
      - ./data/node7:/data
    networks:
      - kadnet

  node8:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node8
      - DATA_DIR=/data
    ports:
      - "8008:8000"
    volumes:
      - ./data/node8:/data
    networks:
      - kadnet

  node9:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node9
      - DATA_DIR=/data
    ports:
      - "8009:8000"
    volumes:
      - ./data/node9:/data
    networks:
      - kadnet

  node10:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node10
      - DATA_DIR=/data
    ports:
      - "8010:8000"
    volumes:
      - ./data/node10:/data
    networks:
      - kadnet

  node11:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node11
      - DATA_DIR=/data
    ports:
      - "8011:8000"
    volumes:
      - ./data/node11:/data
    networks:
      - kadnet

  node12:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node12
      - DATA_DIR=/data
    ports:
      - "8012:8000"
    volumes:
      - ./data/node12:/data
    networks:
      - kadnet

  node13:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node13
      - DATA_DIR=/data
    ports:
      - "8013:8000"
    volumes:
      - ./data/node13:/data
    networks:
      - kadnet

  node14:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node14
      - DATA_DIR=/data
    ports:
      - "8014:8000"
    volumes:
      - ./data/node14:/data
    networks:
      - kadnet

  node15:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node15
      - DATA_DIR=/data
    ports:
      - "8015:8000"
    volumes:
      - ./data/node15:/data
    networks:
      - kadnet

  node16:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node16
      - DATA_DIR=/data
    ports:
      - "8016:8000"
    volumes:
      - ./data/node16:/data
    networks:
      - kadnet

  node17:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node17
      - DATA_DIR=/data
    ports:
      - "8017:8000"
    volumes:
      - ./data/node17:/data
    networks:
      - kadnet

  node18:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node18
      - DATA_DIR=/data
    ports:
      - "8018:8000"
    volumes:
      - ./data/node18:/data
    networks:
      - kadnet

  node19:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node19
      - DATA_DIR=/data
    ports:
      - "8019:8000"
    volumes:
      - ./data/node19:/data
    networks:
      - kadnet

  node20:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node20
      - DATA_DIR=/data
    ports:
      - "8020:8000"
    volumes:
      - ./data/node20:/data
    networks:
      - kadnet

  node21:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node21
      - DATA_DIR=/data
    ports:
      - "8021:8000"
    volumes:
      - ./data/node21:/data
    networks:
      - kadnet

  node22:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node22
      - DATA_DIR=/data
    ports:
      - "8022:8000"
    volumes:
      - ./data/node22:/data
    networks:
      - kadnet

  node23:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node23
      - DATA_DIR=/data
    ports:
      - "8023:8000"
    volumes:
      - ./data/node23:/data
    networks:
      - kadnet

  node24:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node24
      - DATA_DIR=/data
    ports:
      - "8024:8000"
    volumes:
      - ./data/node24:/data
    networks:
      - kadnet

  node25:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node25
      - DATA_DIR=/data
    ports:
      - "8025:8000"
    volumes:
      - ./data/node25:/data
    networks:
      - kadnet

  node26:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node26
      - DATA_DIR=/data
    ports:
      - "8026:8000"
    volumes:
      - ./data/node26:/data
    networks:
      - kadnet

  node27:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node27
      - DATA_DIR=/data
    ports:
      - "8027:8000"
    volumes:
      - ./data/node27:/data
    networks:
      - kadnet

  node28:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node28
      - DATA_DIR=/data
    ports:
      - "8028:8000"
    volumes:
      - ./data/node28:/data
    networks:
      - kadnet

  node29:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node29
      - DATA_DIR=/data
    ports:
      - "8029:8000"
    volumes:
      - ./data/node29:/data
    networks:
      - kadnet

  node30:
    image: "kademlia-nft-node:latest"
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=node30
      - DATA_DIR=/data
    ports:
      - "8030:8000"
    volumes:
      - ./data/node30:/data
    networks:
      - kadnet

networks:
  kadnet:
